### PR TITLE
Petsc

### PR DESCRIPTION
**Pull request by KCallaghan**
@jedbrown here is my current version with some changes to the function and the code for the Jacobian removed. I am running this with `-snes_mf` and getting a (slow) result, which I believe is incorrect (significantly higher water tables compared to previous methods, but as we know previous methods also had issues), but which is at least following the contours of the landscape in a not-totally-unrealistic way. 
Other than the possibly overly-shallow water tables, the water balance is poor, and confirms that water tables are too shallow: I seem to be gaining a large amount of water into the system. 
Finally, very slow runtimes compared to the size of the input data is a problem. Do I need to work on the Jacobian next to improve this, or on something else?

Thank you! - and please ignore the previous tag at this stage.

### CODE REVIEW

**Comment by jedbrown** [comment]
I built it. How can I run the configuration you're running and see these metrics?

**Comment by KCallaghan** [comment]
@jedbrown I have placed sample data and a configuration file [at this link](https://drive.google.com/drive/folders/1rmIfShgTychqURXEv5KK_EZ9KliTkaA3?usp=sharing). 
The two data files - 100_modern_topography.tif and 100_modern_slope.tif - should be placed in a folder called 'surfdata' (or change the file paths in the config file), then run the code with `./build/wtm.x implicit_config_fileA.cfg -snes_mf`. 

The input data is for an artificial 100x100 topography with more or less sinusoidal hills and valleys. 

I have also added two figures at the link - the result of running this code, and the result of running my midpoint method code with the same configuration. Note the significantly deeper water tables with the midpoint method code. 

Other than the water table array, the code will also output a textfile. The last 3 columns in the textfile represent water balance values (recharge in, loss to ocean, and sum of water table).

**Comment by jedbrown** [comment]
Okay, I'm running like this.
```console
$ ../build/wtm.x implicit_config_fileA.cfg -snes_mf -snes_monitor -{snes,ksp}_converged_reason -log_view
Reading configuration file '0x7ffeed0bf5c8'...
0
fdepth_fmin is 2
t Outlets found in = 0.0 s
Before GW time: 2022-06-08 10:20:49
  0 SNES Function norm 1.195111542025e+03
  Linear solve converged due to CONVERGED_RTOL iterations 16
  1 SNES Function norm 1.123788860835e-02
  Linear solve converged due to CONVERGED_RTOL iterations 19
  2 SNES Function norm 6.035100341299e-08
Nonlinear solve converged due to CONVERGED_FNORM_RELATIVE iterations 2
CONVERGED_FNORM_RELATIVE Number of nonlinear iterations = 2
  0 SNES Function norm 4.272138740125e+02
  Linear solve converged due to CONVERGED_RTOL iterations 17
  1 SNES Function norm 2.615415811048e-03
  Linear solve converged due to CONVERGED_RTOL iterations 19
  2 SNES Function norm 1.535656102006e-08
Nonlinear solve converged due to CONVERGED_FNORM_RELATIVE iterations 2
```

The problem is almost linear with this time step (judging by the 5 order of magnitude reduction in residual on the first Newton step of each time step) and we're doing 10 solves per second when I run on a single core. IIRC, the regime you care about will have relatively large subdomains (per process) and you need to take at least one time step per second?

Is the time step here representative of the time step you'll take on a real model? How can we test whether longer time steps impacts accuracy?

**Comment by KCallaghan** [comment]
I have the code looping over the solve 10 times to deal with the non-linearity with the Transmissivity - likely there is a better way to do that - so 10 solves here is one time step. You mention that the problem is almost linear at this time step, but perhaps because I have not represented the nonlinearity of the Transmissivity in an appropriate way? 

I do have the time step here that I would typically use in a real model (1 year), and I would be comfortable going up to 10 years. I think the best checks would be simply (1) comparison to a shorter time step and (2) testing the conservation of water (which is currently very poor). 

This example topography is 100x100 cells and I'd like to run on 11400x23400 cells. Obviously, the faster the better, but I would be very happy with runtimes under 2 minutes per time step for that size. 

For comparison, this code takes me 122 s to run with the example topo/config file I shared; it takes less than 1 second using the midpoint method with the same config file.

**Comment by jedbrown** [comment]
Oh, I'll try to look at the code later today, but I would compute transmissivity on the fly as a function of the state that comes as input to your SNES function. Then SNES will solve the nonlinear problem (probably faster than the 10 iterations you do currently).

**Comment by jedbrown** [comment]
Also, can you run with `-log_view` and send the output to a file? Is your PETSc compiled with optimization, something like `./configure --with-debugging=0 COPTFLAGS='-O3 -march=native'`?

**Comment by KCallaghan** [comment]
@jedbrown well that would make sense... update at 5a00034720398455c4cc34b97cd8edd643e0d45a computes the transmissivity within FormFunction. This is much faster. Results are still significantly different from what I've seen with other methods, so it seems likely that I have a mistake in FormFunction (or elsewhere...)

**Comment by KCallaghan** [comment]
I don't believe that I compiled PETSc with optimisation; I can attempt to do so. 
I have added my log_view output to [the google drive link](https://drive.google.com/drive/folders/1rmIfShgTychqURXEv5KK_EZ9KliTkaA3?usp=sharing).

**Comment by jedbrown** [comment]
```
      ##########################################################
      #                                                        #
      #                       WARNING!!!                       #
      #                                                        #
      #   This code was compiled with a debugging option.      #
      #   To get timing results run ./configure                #
      #   using --with-debugging=no, the performance will      #
      #   be generally two or three times faster.              #
      #                                                        #
      ##########################################################
```
Okay, so this does 10 linear solves per second. The warning here is generally not kidding, but we can make sure we're solving the right problem before digging into that.

**Comment by jedbrown** [comment]
I see some solves that converge like this (normal for Newton) and others that stagnate.  Do you think there may still be a bug in the formulation? 
```
t WTM update time = 1.2
Before GW time: 2022-06-08 23:11:04
  0 SNES Function norm 9.661831510336e+02
  Linear solve converged due to CONVERGED_RTOL iterations 21
  1 SNES Function norm 2.041150530913e+01
  Linear solve converged due to CONVERGED_RTOL iterations 21
  2 SNES Function norm 1.629857319881e-01
  Linear solve converged due to CONVERGED_RTOL iterations 25
  3 SNES Function norm 1.286158119363e-03
  Linear solve converged due to CONVERGED_RTOL iterations 27
  4 SNES Function norm 3.470666650776e-06
Nonlinear solve converged due to CONVERGED_FNORM_RELATIVE iterations 4
CONVERGED_FNORM_RELATIVE Number of nonlinear iterations = 4
```

You can replace your harmonic average with an arithmetic average. That will make the problem less nonlinear since your transmissivity is state dependent. Both are valid discretizations with the same order of accuracy, but the harmonic average might have better constants (or they might be the same since the biggest source of error is elsewhere).

I see you're creating a new SNES each solve. It's better data reuse to set up the SNES and DM once, then just call `SNESSolve` for each solve.

**Comment by KCallaghan** [comment]
I do think there is still something wrong with the formulation, based both on the stagnating solves and on the outputs I am seeing. But, I am not sure if the problem is with the discretisation of the formula, if I still have misunderstood what goes where between the RHS and the SetFunction, or if it's just a garden variety bug in coding. 
I did get more consistent convergence on a2e0f820d772df37c85066012178095f7e5e1fa7, but I then moved the non-linear component of Storativity also into FormFunction. I believe this was the right thing to do, and possibly it was just exposing a problem.

**Comment by KCallaghan** [comment]
I made some changes that were intended to fix problems (most relevant here - the inputs for `updateEffectiveStorativity` should be as water tables relative to the land surface, not as heads) and now I am getting `Linear solve did not converge due to DIVERGED_BREAKDOWN iterations 30`. 
I don't believe this particular change was incorrect, but rather that there is either a problem elsewhere, or correcting this revealed the problem to be far more non-linear. I'm not sure how to troubleshoot this divergence.

**Comment by jedbrown** [comment]
When I use `-ksp_view_eigenvalues`, I see that the operator is indefinite (both positive and negative real parts), which suggests that there is a sign error (because I think this problem should be purely diffusive). You can also add `-ksp_gmres_restart 300` to compute more eigenvalues (default GMRES restart is 30). Can you check the sign and confirm whether the operator should be definite or not?

**Comment by KCallaghan** [comment]
I'm not seeing any sign errors, and I'm not certain whether the operator should be definite or not. 
I do note that if I remove the non-linearity with storativity (by setting storativity always = 1 or always = porosity), then I get convergence and only positive eigenvalues. Possibly this piece is (one of the) problem(s). This is where we try to deal with porosity being = 1 for water above the land surface, and = whatever the cell porosity is below the land surface.

**Comment by KCallaghan** [comment]
@jedbrown I've re-checked the code and tried a few things. 

When I remove the discontinuity storativity, I get convergence, and a result for this test case that looks not unreasonable (though still different from my results with old methods: but starting to convince myself that this new result could be more correct). But, I notice that my mass conservation is very poor. I am seeing hundreds to thousands % loss/gain of water to the system (% is computed relative to the input recharge to the system). Intuitively, it looks as though low topographies in this example are causing water to be pulled in from the ocean down the hydraulic gradient. But, when I go to add up and reset to 0 the changes in ocean cells, I never see a negative change (which would indicate that the continent has gained water from the ocean). Could this be a consequence of the way that boundary conditions in FormFunction are set up, where ocean cells have f = x and land cells have f = (whole formula)? If so, do you know of a good way to compute the true water balance?

When I do include the storativity discontinuity, I get the divergence issues that you have seen. What we are trying to do here is to conserve the water balance by accounting for the fact that porosity should be = 1 above the land surface, but = {porosity} below the land surface. So, not accounting for it does also contribute to the water balance issues. Have you dealt with sharp discontinuities of this kind before?

In my old formulation, I did not try and expect storativity to be perfect; rather, I computed the half-time-step change, doubled it as an estimate of the full time step, set storativity to my estimate for the full time step, and then computed the full time step. I hope that there could be a better way, but if not, would a similar approach here sound reasonable to you? (i.e. solve with set values for storativity, then compute the new storativity based on that result, then repeat the solve).  
I have just tested this idea - only updating the storativity once rather than fully including it in the equation - on my test topography, and at least to my naive eye, the results look good. The system moves toward equilibrium really well, and I can see that the total change in water table is tending towards 0 over time, vs tending toward some non-zero value with oscillations in some cells that we have seen in previous implementations. The water balance problem still exists, but it's conceivable that it's unrelated.

**Comment by jedbrown** [comment]
Sorry I've been a bit unresponsive. I just pulled your latest version and `-ksp_view_eigenvalues` now shows relatively well conditioned definite systems, with very mild asymmetry (perhaps due to grid size variation or boundary conditions)
```console
~/WTM/WTM_test_data$ ../build/wtm.x implicit_config_fileA.cfg -snes_mf -snes_monitor -{snes,ksp}_converged_reason -ksp_view_eigenvalues
[...]
  Linear solve converged due to CONVERGED_RTOL iterations 18
Iteratively computed eigenvalues
1.17442 + 0.i
1.50116 + 0.i
1.96417 + 0.i
2.56361 + 0.i
3.20962 + 0.i
4.26835 + 0.i
5.63154 + 0.i
5.8807 + 0.i
7.09183 + 0.i
7.45864 + 0.i
7.8946 + 0.i
9.33514 + 0.133837i
9.33514 - 0.133837i
10.1978 + 0.i
11.289 + 0.i
12.3054 + 0.i
12.8248 + 0.i
13.229 + 0.i
  3 SNES Function norm 1.892127757214e-07
```

As for sharp discontinuities, these can be tricky, but they should manifest as Newton convergence being degraded despite having exact Jacobians. If the chosen state variable is a very ill conditioned way to represent state (e.g., using density instead of pressure for water), you'll also have linear ill conditioning, but not indefiniteness.

How do the current results look to you? Are all the nonlinearities in the SNES solve or are you still lagging something to update in an outer loop?

**Comment by KCallaghan** [comment]
No problem - it was weekend. 

The current results are starting to look better than before, but there are still some issues. Groundwater and the overall shape of the water table is looking a lot closer to results from previous methods. Ongoing issues include:
1 - I am seeing higher water tables in valley areas (i.e. deeper lakes) compared to old methods; reason still unknown. 
2 - I am not seeing any change in ocean cells. I would expect some groundwater to be lost to/gained from the ocean, and sum this for my water balance, but these cells do not change at all. 
3 - Possibly related to (2), the water balance is poor. 

I am still updating the storativity (which is the piece with the sharp discontinuity) in an outer loop. When I include this in the SNES solve, I still get divergence. Currently I solve, update storativity, solve a second time for each timestep.

**Comment by jedbrown** [comment]
Can we think of the equation as $H(h)_t = \nabla\cdot(T \nabla h) + R$ where $H(h)$ is water-equivalent height?

So if the ground is at elevation $b$ and you have porosity $S$ below the surface, you'd have
$$H(h) = \begin{cases} S(h - b), & h < b,\\\\  h - b, & h > b \end{cases}. $$
We would call $H$ the "conservative variable" and use this interface so that the time integrator will make the "conservative" variable be a polynomial in time (which is probably more physical anyway). https://petsc.org/main/docs/manualpages/TS/DMTSSetTransientVariable/

Conservation here is $(\int H)_t = \int R$. This decouples conservation from the choice of function $H(h)$, which is a continuous function with discontinuous derivative. And one can consider a regularized function in which there is a transition (e.g., within the bottom 3 mm).

**Comment by KCallaghan** [comment]
Do you have any examples using DMTSSetTransientVariable? I'm struggling to actually set it. 
For this, will I need to change my code setup to use TS and SNES together? Something like in [this example](https://petsc.org/main/src/ts/tutorials/ex12.c.html)? Right now I have SNES only, not TS.

**Comment by jedbrown** [comment]
This is a usage example. 
https://petsc.org/main/src/ts/tests/ex15.c.html

It's basically the difference between writing
$$ H_t = H_h h_t = H_h \frac{h^{n+1} - h^n}{\Delta t} = \dotsb $$
versus
$$ H_t = \frac{H(h^{n+1}) - H(h^{n})}{\Delta t} = \dotsb .$$
The latter avoids asking for $H_h = \partial H/\partial h$. You can implement this yourself or using TS. The TS interface allows it to be used with other time integrators, such as BDF methods. Doing it by hand is clear enough for trapezoid rule and implicit Euler, but less obvious for BDF.

**Comment by KCallaghan** [comment]
Thank you! 

I am just trying to understand fully what is being conserved here. Are you saying that this method will force the solution to conserve water within the system throughout time, by balancing recharge with water height? What about loss of water to the ocean? I need to both allow this loss, and record its volume.

**Comment by jedbrown** [comment]
Yeah, you can reset $h$ each time step in the ocean cells. Probably however you do that accounting now is fine. The important thing is to work with $H(h)_t$ instead of $H_h h_t$ since the derivative $H_h$ isn't continuous.

**Comment by KCallaghan** [comment]
Just to update you that I am continuing in attempts to work on TS and a setup with DMTSSetTransientVariable on [this branch](https://github.com/KCallaghan/WTM/tree/petsc_ts). Unfortunately I am running into stubborn issues with passing data around even with a simpler TS setup. I am continuing to try and figure this out.

**Comment by KCallaghan** [comment]
@jedbrown I've resolved my issues with passing data around [on my new branch for the Transient Variable method](https://github.com/KCallaghan/WTM/tree/petsc_ts) and am trying to get the actual math working for this method. As such, I've run into some very basic questions. 

With the method we were working on in [the other PR](https://github.com/KCallaghan/WTM/pull/64#issue-1263850325), I had 3 main parts: DMDASNESSetFunctionLocal, which called FormFunctionLocal and contained my formulation of the groundwater flow equation; FormInitialGuess, where I set a starting water table guess, and FormRHS, where I set the current water table + recharge. 

In the example for Transient Variables, I can only see two parts where math goes: DMTSSetIFunction and DMTSSetTransientVariable. Unfortunately I am not finding the manual pages for these two pieces to be very helpful. For DMTSSetIFunction: "set TS implicit function evaluation function". Should this be similar/the same as the groundwater flow equation I previously had in DMDASNESSetFunctionLocal, or do I need to transform this function into something else for the method? 
DMTSSetTransientVariable: "sets function to transform from state to transient variables". My understanding from what you said previously was that this is where to set the thing to be conserved - but it is not clear how. Are 'conservative' and 'transient' variable referring to the same variable here? 

It is clear that the setup I currently have is not working and that I am not correctly understanding what needs to be in each of these functions - or if I need to be using an additional TS and/or SNES function to hold one of these pieces while DMTSSetTransientVariable and DMTSSetIFunction do something different. 

Thank you!

**Comment by jedbrown** [comment]
Sorry about the docs. We recently moved what had been a LaTeX (PDF) users manual into Sphinx and can now link it from man pages, but lots of man pages haven't been visited for that. The manual has some further description. https://petsc.org/main/docs/manual/ts/

In short, you'll be writing your equation in the form $F(t, u, u_t) = 0$. Since you will be setting the transient variable, this is like $F(t, h, H_t) = 0$ where $H(h)$ is your transient variable. So your IFunction would be
$$ F(t, h, H_t) = H_t - \nabla\cdot(T \nabla h) - R . $$

"Conservative" and "transient" here are the same thing, $H(h)$. ("Transient" refers to the structural position in TS. The motivating reason for using this form is conservation, but a user could opt to use the integrator in this way with a variable that was not "conservative".)

I'd recommend using [`DMDATSSetIFunctionLocal`](https://petsc.org/main/docs/manualpages/TS/DMDATSSetIFunctionLocal/).

**Comment by KCallaghan** [comment]
@jedbrown thank you for that information. 
Unfortunately, I am still running into problems. In c063eb4c022a13e8e271e90659c2c549349f9c05, ```DMTSSetTransientVariable``` doesn't seem to actually do anything (or possibly the result is not being applied to ```DMDATSSetIFunctionLocal``` appropriately). The output is a set, nonsensical value over the entire domain. Do you have any suggestions?

**Comment by jedbrown** [comment]
I'll make a better error message in PETSc, but the transient variable stuff is currently only supported for the BDF family. I don't know how to interpret output from your test code, but it should be using the transient variable if you apply this patch.
```diff
diff --git a/src/CreateSNES.cpp b/src/CreateSNES.cpp
index 9f45025..3101c7f 100644
--- a/src/CreateSNES.cpp
+++ b/src/CreateSNES.cpp
@@ -3,6 +3,8 @@
 void InitialiseSNES(AppCtx& user_context, Parameters& params) {
   // SNESCreate(PETSC_COMM_WORLD, &user_context.snes);
   TSCreate(PETSC_COMM_WORLD, &user_context.ts);
+  TSSetType(user_context.ts, TSBDF);
+  TSBDFSetOrder(user_context.ts, 1); // BDF1 = Backward Euler

   user_context.cellsize_NS = params.cellsize_n_s_metres;
   user_context.timestep    = params.deltat;
```

I see `TransientVar` just does a copy now, but you'll want to make it compute $H(h)$.

**Comment by KCallaghan** [comment]
Thanks - unfortunately, my current problem is persisting. The values that I set for `Xdot` in `TransientVar` are not seen in `FormIFunctionLocal`. It seems like I must be doing something wrong with data i/o in these functions?

**Comment by jedbrown** [comment]
How would I go about reproducing what you're seeing? Like how do you run and what are you looking at?

**Comment by KCallaghan** [comment]
I am running `./build/wtm.x config_file.cfg -snes_mf -snes_monitor -{snes,ksp}_converged_reason -log_view` 
The code is currently printing sample values to the screen. For example, `x in the func before 703.08 f 0 xdot 0`
But xdot values should be non-zero after being set in `TransientVar`, therefore this seems to not be accessing the array I have set in `TransientVar`.

**Comment by jedbrown** [comment]
So for BDF1 (backward Euler), the calculation looks like $H_t = \frac{H(h^{n+1}) - H(h^n)}{\Delta t}$ and since you write $H(\cdot) = 100$ uniformly, these cancel exactly and you get $H_t = 0$. You get nontrivial $H_t$ if you apply this patch. (Feel free to give me push access if you'd rather I just push these changes.)

I see there is a double free that I don't understand yet in this case. Maybe I can look after kid bedtime. Note that DMDA arrays are indexed as `x[j][i]` rather than `x[i][j]`.

```diff
diff --git a/src/transient_groundwater.cpp b/src/transient_groundwater.cpp
index 7c5ea0a..c6584b2 100644
--- a/src/transient_groundwater.cpp
+++ b/src/transient_groundwater.cpp
@@ -165,25 +165,26 @@ static PetscErrorCode FormIFunctionLocal(
   return 0;
 }

-static PetscErrorCode TransientVar(TS ts, Vec X, Vec Xdot, void* ctx) {
+static PetscErrorCode TransientVar(TS ts, Vec Head, Vec Thickness, void* ctx) {
   AppCtx* user_context = (AppCtx*)ctx;
   DM da                = user_context->da;
   // const PetscScalar* cdot;
   PetscInt xs, ys, xm, ym;
-  PetscScalar **starting_storativity, **cellsize_ew, **my_mask, **my_fdepth, **my_ksat, **my_h, **my_porosity,
-      **my_topo, **my_rech, **my_area, **x, **xdot;
-  PetscCall(DMDAVecGetArray(da, Xdot, &xdot));
+  const PetscScalar **h;
+  PetscScalar **starting_storativity, **cellsize_ew, **my_mask, **my_fdepth, **my_ksat, **H, **my_porosity,
+      **my_topo, **my_rech, **my_area;
+  PetscCall(DMDAVecGetArrayRead(da, Head, &h));
+  PetscCall(DMDAVecGetArrayWrite(da, Thickness, &H));

   DMDAGetCorners(da, &xs, &ys, NULL, &xm, &ym, NULL);
   for (auto j = ys; j < ys + ym; j++) {
     for (auto i = xs; i < xs + xm; i++) {
-      xdot[i][j] = 100;
+      H[j][i] = h[j][i];
     }
   }

-  PetscCall(DMDAVecRestoreArray(da, Xdot, &xdot));
-
-  // PetscCall(VecCopy(X, Xdot));
+  PetscCall(DMDAVecRestoreArrayRead(da, Head, &h));
+  PetscCall(DMDAVecRestoreArrayWrite(da, Thickness, &H));

   return 0;
 }
```

**Comment by KCallaghan** [comment]
Oh, wow. I was really misunderstanding what needed to go in `TransientVar`! I thought that the values I was setting there should be the values I saw coming into `FormIFunctionLocal`, no wonder I couldn't get that to happen. 

Okay, I'm getting **a** result out now, but not a correct one. My next questions are about timestepping with TS. 

- When I do something with a timestep, for example, set its length using `TSSetTimeStep(ts, timestep)`, is this timestep in seconds? 
- My understanding is that TS is capable of adaptive timestepping. Should I be doing this? Will it select the longest timesteps possible? And if yes, where do I start with this?
- When I have time-dependent inputs, for example, recharge [m/s], should I be adding this for the length of time set either in `TSSetTimeStep` or with the adaptive timestep length? This one feels obvious, but I wondered if I needed to do this for the length set in `TSSetMaxTime` instead. 
- Right now, I am trying to set my timestep = 31536000 (~ seconds in a year). However, I am seeing `CONVERGED_ITS at time 1e+07 after 10000 steps`, which is a shorter timestep. Why would this happen?
- After that first timestep, solves stop happening and I see `CONVERGED_ITS at time 0. after 10000 steps`. Any idea why this might happen?

The behaviour I'm currently seeing looks visually as though the water is moving for a shorter amount of time than I expect it to - but, if I have the timestepping parts right, then this could still be due to me coding some gradient piece of the formula incorrectly.

**Comment by jedbrown** [comment]
The time step is in whatever units you use. Diffusivity in the PDE has units of $[\text{length}]^2/[\text{time}]$ and your source terms also have time units. You might find that length 1 km and time in years are reasonable scales, but you can choose all SI.

TSSolve can do adaptive time stepping, but it sounds like you intend to call it once per time step rather than once per simulation. You can use `TSStep` as a more direct interface.

You can use `-ts_adapt_monitor` or `-ts_monitor` to see what's happening each step or `-ts_view` to see the solver configuration. What might be happening is that TSSolve continues stepping from the "current time", but if you don't extend the "max time", it'll think it's done already. TSStep has less such logic, or you can arrange your app to call TSSolve once for a whole simulation and use `TSSetPostStage` or `TSSetPostStep` to do your non-PDE projection stuff.

**Comment by KCallaghan** [comment]
Okay, this makes sense for the timestep, and I seem to have fixed the most obvious issues I was having with that by resetting the TS time & step number at each timestep. I'm not entirely convinced that it will be possible to call TSSolve only once per year (i.e. that it will successfully solve at this rate), but that's probably something to come back to once other parts are working as expected. 

In that case, I suspect that I still have a math problem, possibly still by not putting the transient variable and i-function pieces together correctly. 

In summary, this is what I am doing right now (b5285bcde36fce4d89610fff46065fbc9aae8b84): 

Set the initial solution:
$x = h    $,
where h is head and is equal to (topography + water table depth)

Set the transient variable:

$H = (h - topo) * S $,
where S is the storativity, and is equal to 1 above the land surface and some value between 0 and 1 below the land surface. 

i-function:
$f  = H - \nabla\cdot(T \nabla h) - R . $

Results are not what I expect: I tend to get values that are too large after the first timestep (positive values for water table depth across the whole domain where I expect a mix of positive and negative), then after the second timestep, the opposite with very negative values. Values will then climb up to the land surface in subsequent timesteps before plummeting again in the step after they become positive. 

I'm hoping that my mistake may be obvious to you?

**Comment by jedbrown** [comment]
Sorry I've been nonresponsive. Perhaps it's a typo here, but IFunction gets two state arguments, which here when using "transient variables" will be $H_t$ and $h$. So you'll write $f = H_t - \nabla\cdot(T \nabla h) - R .$

Is there a configuration I can run to try to understand? Is it possible to run a simpler configuration, maybe with S=1 uniformly so we can remove that source of difficulty interpreting the model?

**Comment by KCallaghan** [comment]
Yes, that is what I have done (or rather, attempted to do, since it does not work as expected). 

My commit at 7d393f6772162b33bcdf3baabc5336d6043e964d has S=1. 

I am continuing to use the input and configuration files at [this link](https://drive.google.com/drive/folders/1rmIfShgTychqURXEv5KK_EZ9KliTkaA3?usp=sharing). I run with `./build/wtm.x Config_fileA.cfg -snes_mf`. Thank you for any ideas!

**Pull request merged**
